const mongoose = require('mongoose');


const HotelProfileSchema = mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    name:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    popularcity:{
        type:String,
        required:true
    },
    todaybestoffer:{
        type:String
    },
    description:[],
    phonenumber:{
        type:String,
        required:true
    },
    date:{
        type:Date,
        default:Date.now
    },
    profilepicture:{
        type:String
    },
    rooms:[
        {
            category:{
                type:String,
                required:true
            },
            price:{
                type:String,
                required:true
            },
            phonenumber:{
                type:String
            },
            facilities:{
                type:String
            },
            ac:{
                type:Boolean,
                required:true
            },
            description:{
                type:String
            },
            images:[]
        }
    ],
    restuarant:[
        {
            foodname:{
                type:String,
                required:true
            },
            foodImages:[],
            price:{
                type:String,
                required:true
            },
            description:{
                type:String
            }
        }
    ],
    weddinghall:[
        {
            price:{
                type:String,
                required:true
            },
            description:{
                type:String
            },
            phonenumber:{
                type:String,
                required:true
            },
            hallname:{
                type:String,
                required:true
            },
            included:[],
            hallimages:[]
        }
    ],
    comments:[
        {
            text:
            {
                type:String
            }
    }
    ]

})

module.exports= Hotel = mongoose.model('hotelprofile', HotelProfileSchema);